Repository worldwide-asset-exchange/atomicassets-api, pull requests merged in 2022-03, with the labels that each got.

#3 Feat()/Update eosio-contract-api v1.3.9
  CODEOWNERS
  definitions/migrations/1.2.0/script.js
  definitions/migrations/1.2.1/script.js
  definitions/migrations/1.2.14/script.js
  definitions/migrations/1.2.2/script.js
  definitions/migrations/1.2.3/script.js
  definitions/migrations/1.2.4/script.js
  definitions/migrations/1.2.5/script.js
  definitions/migrations/1.3.0/script.js
  definitions/migrations/1.3.1/script.js
  definitions/migrations/1.3.3/script.js
  definitions/migrations/1.3.4/script.js
  definitions/migrations/1.3.5/script.js
  definitions/migrations/1.3.7/atomicassets.sql
  definitions/migrations/1.3.7/database.sql
  definitions/migrations/1.3.8/database.sql
  definitions/migrations/1.3.9/atomicassets.sql
  definitions/migrations/1.3.9/atomicmarket.sql
  definitions/migrations/1.3.9/database.sql
  definitions/tables/base_tables.sql
  package.json
  src/api/namespaces/atomicassets/format.ts
  src/api/namespaces/atomicassets/handlers/collections.ts
  src/api/namespaces/atomicassets/handlers/schemas.ts
  src/api/namespaces/atomicassets/index.ts
  src/api/namespaces/atomicassets/utils.ts
  src/api/namespaces/atomicmarket/handlers/sales2.test.ts
  src/api/namespaces/atomicmarket/handlers/sales2.ts
  src/api/namespaces/atomicmarket/handlers/stats.ts
  src/api/namespaces/atomicmarket/index.ts
  src/api/namespaces/atomictools/index.ts
  src/connections/redis.ts
  src/filler/database.test.ts
  src/filler/jobqueue.test.ts
  src/filler/upgrade-db.ts
  yarn.lock
Labels: patch

#6 Feat()/Introduce atomic database health check
  src/api/server.ts
Labels: minor

#7 Fix()/Revert a98b3ed 8b16975
  src/api/server.ts
Labels: patch

#9 Revert server.ts
  src/api/server.ts
Labels: patch

#5 Feat()/Update eosio-contract-api v1.3.10
  config/example-server.config.json
  package.json
  src/api/namespaces/atomicassets/handlers/accounts.ts
  src/api/namespaces/atomicassets/handlers/burns.ts
  src/api/namespaces/atomicassets/handlers/collections.ts
  src/api/namespaces/atomicassets/openapi.ts
  src/api/namespaces/atomicassets/routes/accounts.ts
  src/api/namespaces/atomicassets/routes/assets.ts
  src/api/namespaces/atomicassets/routes/burns.ts
  src/api/namespaces/atomicassets/routes/offers.ts
  src/api/namespaces/atomicassets/routes/transfers.ts
  src/api/namespaces/atomicmarket/routes/auctions.ts
  src/api/namespaces/atomicmarket/routes/buyoffers.ts
  src/api/namespaces/atomicmarket/routes/sales.ts
  src/api/notification.ts
  src/api/server.ts
  src/api/utils.ts
  src/bin/server.ts
Labels: minor, automerge
